"""
Data Transfer Objects (DTOs) for Aircraft entities.
"""
from enum import Enum
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field


class AircraftStatus(str, Enum):
    """
    Enum representing the operational state of an aircraft.
    """
    AVAILABLE = "AVAILABLE"
    DEPLOYED = "DEPLOYED"
    AOG = "MAINTENANCE"


class AircraftBase(BaseModel):
    """
    Base properties shared across all Aircraft schemas.
    """
    manufacturer: str = Field(..., description="The company that built the aircraft (e.g., Boeing)")
    aircraft_model: str = Field(..., description="The specific model designation (e.g., 737-800)")
    current_distance: float = Field(0.0, description="Total distance flown since last maintenance cycle")
    maintenance_interval: float = Field(..., description="Maximum distance allowed before required maintenance")
    aircraft_status: AircraftStatus = Field(AircraftStatus.AVAILABLE)
    aircraft_location: str = Field(..., description="Current IATA airport code location")


class AircraftCreate(AircraftBase):
    """
    Schema for creating a new Aircraft. 
    Does not include aircraft_id as it is generated by the database.
    """
    pass


class AircraftRead(AircraftBase):
    """
    Schema for representing an Aircraft in API responses.
    Includes the unique identifier and ORM compatibility.
    """
    aircraft_id: UUID

    model_config = ConfigDict(
        from_attributes=True,  # Replaces 'from_orm = True'
        json_schema_extra={
            "example": {
                "aircraft_id": "550e8400-e29b-41d4-a716-446655440000",
                "manufacturer": "Airbus",
                "aircraft_model": "A320",
                "current_distance": 500.5,
                "maintenance_interval": 5000.0,
                "aircraft_status": "AVAILABLE",
                "aircraft_location": "ORD"
            }
        }
    )