"""init

Revision ID: 437009c7fba0
Revises: 
Create Date: 2026-02-11 18:44:08.753517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437009c7fba0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('airline_designator', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('airline_designator')
    )
    op.create_table('airport',
    sa.Column('airport_code', sa.UUID(), nullable=False),
    sa.Column('airport_name', sa.String(), nullable=False),
    sa.Column('airport_country', sa.String(), nullable=False),
    sa.Column('airport_city', sa.String(), nullable=False),
    sa.Column('airport_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('airport_code')
    )
    op.create_table('aircraft',
    sa.Column('aircraft_id', sa.UUID(), nullable=False),
    sa.Column('airline_designator', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('aircraft_model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['airline_designator'], ['airline.airline_designator'], ),
    sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_table('in_flight_employee',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('IATA_code', sa.String(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('CAPTAIN', 'COPILOT', 'MANAGER', 'FLIGHT_ATTENDANT', name='employeeposition'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('supervised', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IATA_code'], ['airline.airline_designator'], ),
    sa.ForeignKeyConstraint(['supervised'], ['in_flight_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('operates',
    sa.Column('airline_designator', sa.String(), nullable=False),
    sa.Column('airport_code', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['airline_designator'], ['airline.airline_designator'], ),
    sa.ForeignKeyConstraint(['airport_code'], ['airport.airport_code'], ),
    sa.PrimaryKeyConstraint('airline_designator', 'airport_code')
    )
    op.create_table('route',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('destination_airport_code', sa.String(), nullable=True),
    sa.Column('origin_airport_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['destination_airport_code'], ['airport.airport_code'], ),
    sa.ForeignKeyConstraint(['origin_airport_code'], ['airport.airport_code'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('flight_status', sa.Enum('SCHEDULED', 'BOARDING', 'DEPARTED', 'EN_ROUTE', 'ARRIVED', 'COMPLETED', 'CANCELED', name='flightstatus'), nullable=True),
    sa.Column('aircraft_id', sa.UUID(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('dept_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.aircraft_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('flight_crew',
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['in_flight_employee.employee_id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], ),
    sa.PrimaryKeyConstraint('flight_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_crew')
    op.drop_table('flight')
    op.drop_table('route')
    op.drop_table('operates')
    op.drop_table('in_flight_employee')
    op.drop_table('aircraft')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
