"""init

Revision ID: 4e31e538a741
Revises: 259e1656305e
Create Date: 2026-02-16 14:43:00.742237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e31e538a741'
down_revision: Union[str, Sequence[str], None] = '259e1656305e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'manufacturer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('aircraft', 'aircraft_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('aircraft', 'current_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('aircraft', 'maintenance_interval',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('aircraft', 'aircraft_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'DEPLOYED', 'AOG', name='aircraftstatus'),
               nullable=False)
    op.alter_column('airport', 'airport_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airport', 'airport_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airport', 'airport_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airport', 'airport_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airport', 'longitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airport', 'latitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flight', 'flight_status',
               existing_type=postgresql.ENUM('SCHEDULED', 'IN_FLIGHT', 'ARRIVED', 'DELAYED', 'CANCELLED', name='flightstatus'),
               nullable=False)
    op.alter_column('flight', 'arrival_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('flight', 'departure_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('in_flight_employee', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('in_flight_employee', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('in_flight_employee', 'position',
               existing_type=postgresql.ENUM('CAPTAIN', 'COPILOT', 'FLIGHT_MANAGER', 'FLIGHT_ATTENDANT', name='employeeposition'),
               nullable=False)
    op.alter_column('in_flight_employee', 'employee_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'SCHEDULED', name='inflightstatus'),
               nullable=False)
    op.alter_column('in_flight_employee', 'supervisor',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('in_flight_employee', 'supervisor',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('in_flight_employee', 'employee_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'SCHEDULED', name='inflightstatus'),
               nullable=True)
    op.alter_column('in_flight_employee', 'position',
               existing_type=postgresql.ENUM('CAPTAIN', 'COPILOT', 'FLIGHT_MANAGER', 'FLIGHT_ATTENDANT', name='employeeposition'),
               nullable=True)
    op.alter_column('in_flight_employee', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('in_flight_employee', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flight', 'departure_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flight', 'arrival_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('flight', 'flight_status',
               existing_type=postgresql.ENUM('SCHEDULED', 'IN_FLIGHT', 'ARRIVED', 'DELAYED', 'CANCELLED', name='flightstatus'),
               nullable=True)
    op.alter_column('airport', 'latitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airport', 'longitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airport', 'airport_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airport', 'airport_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airport', 'airport_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airport', 'airport_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('aircraft', 'aircraft_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'DEPLOYED', 'AOG', name='aircraftstatus'),
               nullable=True)
    op.alter_column('aircraft', 'maintenance_interval',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('aircraft', 'current_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('aircraft', 'aircraft_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('aircraft', 'manufacturer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
